spring:
  application:
    name: booking-server-query
  elasticsearch:
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD}
    uris: ${ELASTIC_URIS}
  data:
    elasticsearch:
      repositories:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
server:
  port: ${SERVER_PORT:8081}
  address: ${SERVER_ADDRESS:0.0.0.0}
  error:
    include-message: always

logging:
  level:
    root: error

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD}
spring.url: ${SPRING_URL:http://localhost:8084}
